#!/bin/sh

# Copyright © 2017 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

export LC_ALL=C.UTF-8
export DEBIAN_FRONTEND=noninteractive
cat > /etc/apt/apt.conf.d/99local <<EOF
APT::Install-Recommends "false";
Apt::Get::Purge "true";
Apt::Get::Show-Versions "true";
Acquire::Languages "none";
EOF
apt-get update
apt-get dist-upgrade -y
apt-get install -y locales-all mosh
adduser --disabled-password --gecos 'Jakub Wilk' jwilk
su jwilk -c 'mkdir -m 700 ~/.ssh'
cat .ssh/authorized_keys | su jwilk -c 'cat > ~/.ssh/authorized_keys'
